import emoji

# print(emoji.emojize(':bowtie:'))
# print(emoji.emojize(':smile:'))
# print(emoji.emojize(':simple_smile:'))
# print(emoji.emojize(':laughing:'))
# print(emoji.emojize(':blush:'))
# print(emoji.emojize(':smiley:'))
# print(emoji.emojize(':relaxed:'))
# print(emoji.emojize(':smirk:'))
# print(emoji.emojize(':heart_eyes:'))
# print(emoji.emojize(':kissing_heart:'))
# print(emoji.emojize(':kissing_closed_eyes:'))
# print(emoji.emojize(':flushed:'))
# print(emoji.emojize(':relieved:'))
# print(emoji.emojize(':satisfied:'))
# print(emoji.emojize(':grin:'))
# print(emoji.emojize(':wink:'))
# print(emoji.emojize(':stuck_out_tongue_winking_eye:'))
# print(emoji.emojize(':stuck_out_tongue_closed_eyes:'))
# print(emoji.emojize(':grinning:'))
# print(emoji.emojize(':kissing:'))
# print(emoji.emojize(':kissing_smiling_eyes:'))
# print(emoji.emojize(':stuck_out_tongue:'))
# print(emoji.emojize(':sleeping:'))
# print(emoji.emojize(' :worried:'))
# print(emoji.emojize(':frowning:'))
# print(emoji.emojize(':anguished:'))
# print(emoji.emojize(':open_mouth:'))
# print(emoji.emojize(':grimacing:'))
# print(emoji.emojize(':confused:'))
# print(emoji.emojize(':hushed:'))
# print(emoji.emojize(':expressionless:'))
# print(emoji.emojize(':unamused:'))
# print(emoji.emojize(':sweat_smile:'))
# print(emoji.emojize(':sweat:'))
# print(emoji.emojize(':disappointed_relieved:'))
# print(emoji.emojize(':weary:'))
# print(emoji.emojize(':pensive:'))
# print(emoji.emojize(':disappointed:'))
# print(emoji.emojize(':confounded:'))
# print(emoji.emojize(':fearful:'))
# print(emoji.emojize(':cold_sweat:'))
# print(emoji.emojize(':persevere:'))
# print(emoji.emojize(':cry:'))
# print(emoji.emojize(':sob:'))
# print(emoji.emojize(':joy:'))
# print(emoji.emojize(':astonished:'))
# print(emoji.emojize(':scream:'))
# print(emoji.emojize(':neckbeard:'))
print(emoji.emojize(':tired_face:'))
# print(emoji.emojize(':angry:'))
# print(emoji.emojize(':rage:'))
# print(emoji.emojize(':triumph:'))
# print(emoji.emojize(':sleepy:'))
# print(emoji.emojize(':yum:'))
# print(emoji.emojize(':mask:'))
print(emoji.emojize(':sunglasses:'))
print(emoji.emojize(':dizzy_face:'))
# print(emoji.emojize(':imp:'))
# print(emoji.emojize(':smiling_imp:'))
print(emoji.emojize(':neutral_face:'))
# print(emoji.emojize(':no_mouth:'))
# print(emoji.emojize(':innocent:'))
print(emoji.emojize(':alien:'))
print(emoji.emojize(':yellow_heart:'))
print(emoji.emojize(':blue_heart:'))
print(emoji.emojize(':purple_heart:'))
# print(emoji.emojize(':heart:'))
print(emoji.emojize(':green_heart:'))
print(emoji.emojize(':broken_heart:'))
# print(emoji.emojize(':heartbeat:'))
# print(emoji.emojize(':heartpulse:'))
print(emoji.emojize(':two_hearts:'))
print(emoji.emojize(':revolving_hearts:'))
# print(emoji.emojize(':cupid:'))
print(emoji.emojize(':sparkling_heart:'))
print(emoji.emojize(':sparkles:'))
# print(emoji.emojize(':star:'))
# print(emoji.emojize(':star2:'))
print(emoji.emojize(':dizzy:'))
# print(emoji.emojize(':boom:'))
print(emoji.emojize(':collision:'))
# print(emoji.emojize(':anger:'))
# print(emoji.emojize(':exclamation:'))
# print(emoji.emojize(':question:'))
# print(emoji.emojize(':grey_exclamation:'))
# print(emoji.emojize(':grey_question:'))
print(emoji.emojize(':zzz:'))
# print(emoji.emojize(':dash:'))
# print(emoji.emojize(':sweat_drops:'))
# print(emoji.emojize(':notes:'))
print(emoji.emojize(':musical_note:'))
print(emoji.emojize(':fire:'))
# print(emoji.emojize(':hankey:'))
# print(emoji.emojize(':poop:'))
# print(emoji.emojize(':shit:'))
# print(emoji.emojize(':+1:'))
# print(emoji.emojize(':thumbsup:'))
# print(emoji.emojize(':-1:'))
# print(emoji.emojize(':thumbsdown:'))
# print(emoji.emojize(':ok_hand:'))
# print(emoji.emojize(':punch:'))
# print(emoji.emojize(':facepunch:'))
# print(emoji.emojize(':fist:'))
# print(emoji.emojize(':v:'))
# print(emoji.emojize(':wave:'))
# print(emoji.emojize(':hand:'))
print(emoji.emojize(':raised_hand:'))
print(emoji.emojize(':open_hands:'))
# print(emoji.emojize(':point_up:'))
# print(emoji.emojize(':point_down:'))
# print(emoji.emojize(':point_left:'))
# print(emoji.emojize(':point_right:'))
# print(emoji.emojize(':raised_hands:'))
# print(emoji.emojize(':pray:'))
# print(emoji.emojize(':point_up_2:'))
# print(emoji.emojize(':clap:'))
# print(emoji.emojize(':muscle:'))
# print(emoji.emojize(':metal:'))
# print(emoji.emojize(':fu:'))
# print(emoji.emojize(':runner:'))
# print(emoji.emojize(':running:'))
# print(emoji.emojize(':couple:'))
print(emoji.emojize(':family:'))
print(emoji.emojize(':two_men_holding_hands:'))
print(emoji.emojize(':two_women_holding_hands:'))
# print(emoji.emojize(':dancer:'))
# print(emoji.emojize(':dancers:'))
# print(emoji.emojize(':ok_woman:'))
# print(emoji.emojize(':no_good:'))
# print(emoji.emojize(':information_desk_person:'))
# print(emoji.emojize(':raising_hand:'))
print(emoji.emojize(':bride_with_veil:'))
# print(emoji.emojize(':person_with_pouting_face:'))
print(emoji.emojize(':person_frowning:'))
# print(emoji.emojize(':bow:'))
# print(emoji.emojize(':couplekiss:'))
print(emoji.emojize(':couple_with_heart:'))
# print(emoji.emojize(':massage:'))
# print(emoji.emojize(':haircut:'))
# print(emoji.emojize(':nail_care:'))
print(emoji.emojize(':boy:'))
print(emoji.emojize(':girl:'))
print(emoji.emojize(':woman:'))
print(emoji.emojize(':man:'))
print(emoji.emojize(':baby:'))
# print(emoji.emojize(':older_woman:'))
# print(emoji.emojize(':older_man:'))
# print(emoji.emojize(':person_with_blond_hair:'))
# print(emoji.emojize(':man_with_turban:'))
print(emoji.emojize(':construction_worker:'))
# print(emoji.emojize(':cop:'))
# print(emoji.emojize(':angel:'))
print(emoji.emojize(':princess:'))
# print(emoji.emojize(':smiley_cat:'))
# print(emoji.emojize(':smile_cat:'))
# print(emoji.emojize(':heart_eyes_cat:'))
# print(emoji.emojize(':kissing_cat:'))
# print(emoji.emojize(':smirk_cat:'))
# print(emoji.emojize(':scream_cat:'))
print(emoji.emojize(':crying_cat_face:'))
# print(emoji.emojize(':joy_cat:'))
# print(emoji.emojize(':pouting_cat:'))
# print(emoji.emojize(':japanese_ogre:'))
# print(emoji.emojize(':japanese_goblin:'))
# print(emoji.emojize(':see_no_evil:'))
# print(emoji.emojize(':hear_no_evil:'))
# print(emoji.emojize(':speak_no_evil:'))
# print(emoji.emojize(':guardsman:'))
print(emoji.emojize(':skull:'))
# print(emoji.emojize(':feet:'))
# print(emoji.emojize(':lips:'))
print(emoji.emojize(':kiss:'))
print(emoji.emojize(':droplet:'))
print(emoji.emojize(':ear:'))
print(emoji.emojize(':eyes:'))
print(emoji.emojize(':nose:'))
print(emoji.emojize(':tongue:'))
print(emoji.emojize(':love_letter:'))
print(emoji.emojize(':bust_in_silhouette:'))
print(emoji.emojize(':busts_in_silhouette:'))
print(emoji.emojize(':speech_balloon:'))
print(emoji.emojize(':thought_balloon:'))
# print(emoji.emojize(':feelsgood:'))
# print(emoji.emojize(':finnadie:'))
# print(emoji.emojize(':goberserk:'))
# print(emoji.emojize(':godmode:'))
# print(emoji.emojize(':hurtrealbad:'))
# print(emoji.emojize(':rage1:'))
# print(emoji.emojize(':rage2:'))
# print(emoji.emojize(':rage3:'))
# print(emoji.emojize(':rage4:'))
# print(emoji.emojize(':suspect:'))
# print(emoji.emojize(':trollface:'))

# print(emoji.emojize(':sunny:'))
print(emoji.emojize(':umbrella:'))
print(emoji.emojize(':cloud:'))
print(emoji.emojize(':snowflake:'))
print(emoji.emojize(':snowman:'))
# print(emoji.emojize(':zap:'))
print(emoji.emojize(':cyclone:'))
print(emoji.emojize(':foggy:'))
# print(emoji.emojize(':ocean:'))
print(emoji.emojize(':cat:'))
print(emoji.emojize(':dog:'))
print(emoji.emojize(':mouse:'))
# print(emoji.emojize(':hamster:'))
print(emoji.emojize(':rabbit:'))
# print(emoji.emojize(':wolf:'))
# print(emoji.emojize(':frog:'))
print(emoji.emojize(':tiger:'))
print(emoji.emojize(':koala:'))
# print(emoji.emojize(':bear:'))
print(emoji.emojize(':pig:'))
print(emoji.emojize(':pig_nose:'))
print(emoji.emojize(':cow:'))
print(emoji.emojize(':boar:'))
print(emoji.emojize(':monkey_face:'))
print(emoji.emojize(':monkey:'))
print(emoji.emojize(':horse:'))
# print(emoji.emojize(':racehorse:'))
print(emoji.emojize(':camel:'))
# print(emoji.emojize(':sheep:'))
print(emoji.emojize(':elephant:'))
print(emoji.emojize(':panda_face:'))
print(emoji.emojize(':snake:'))
print(emoji.emojize(':bird:'))
print(emoji.emojize(':baby_chick:'))
# print(emoji.emojize(':hatched_chick:'))
print(emoji.emojize(':hatching_chick:'))
print(emoji.emojize(':chicken:'))
print(emoji.emojize(':penguin:'))
print(emoji.emojize(':turtle:'))
print(emoji.emojize(':bug:'))
print(emoji.emojize(':honeybee:'))
print(emoji.emojize(':ant:'))
# print(emoji.emojize(':beetle:'))
print(emoji.emojize(':snail:'))
print(emoji.emojize(':octopus:'))
print(emoji.emojize(':tropical_fish:'))
print(emoji.emojize(':fish:'))
print(emoji.emojize(':whale:'))
# print(emoji.emojize(':whale2:'))
print(emoji.emojize(':dolphin:'))
# print(emoji.emojize(':cow2:'))
print(emoji.emojize(':ram:'))
print(emoji.emojize(':rat:'))
print(emoji.emojize(':water_buffalo:'))
# print(emoji.emojize(':tiger2:'))
# print(emoji.emojize(':rabbit2:'))
print(emoji.emojize(':dragon:'))
print(emoji.emojize(':goat:'))
print(emoji.emojize(':rooster:'))
# print(emoji.emojize(':dog2:'))
# print(emoji.emojize(':pig2:'))
# print(emoji.emojize(':mouse2:'))
print(emoji.emojize(':ox:'))
print(emoji.emojize(':dragon_face:'))
print(emoji.emojize(':blowfish:'))
print(emoji.emojize(':crocodile:'))
# print(emoji.emojize(':dromedary_camel:'))
print(emoji.emojize(':leopard:'))
# print(emoji.emojize(':cat2:'))
print(emoji.emojize(':poodle:'))
print(emoji.emojize(':paw_prints:'))
print(emoji.emojize(':bouquet:'))
print(emoji.emojize(':cherry_blossom:'))
print(emoji.emojize(':tulip:'))
print(emoji.emojize(':four_leaf_clover:'))
print(emoji.emojize(':rose:'))
print(emoji.emojize(':sunflower:'))
print(emoji.emojize(':hibiscus:'))
print(emoji.emojize(':maple_leaf:'))
# print(emoji.emojize(':leaves:'))
print(emoji.emojize(':fallen_leaf:'))
print(emoji.emojize(':herb:'))
print(emoji.emojize(':mushroom:'))
print(emoji.emojize(':cactus:'))
print(emoji.emojize(':palm_tree:'))
print(emoji.emojize(':evergreen_tree:'))
print(emoji.emojize(':deciduous_tree:'))
print(emoji.emojize(':chestnut:'))
print(emoji.emojize(':seedling:'))
print(emoji.emojize(':blossom:'))
# print(emoji.emojize(':ear_of_rice:'))
# print(emoji.emojize(':shell:'))
print(emoji.emojize(':globe_with_meridians:'))
print(emoji.emojize(':sun_with_face:'))
# print(emoji.emojize(':full_moon_with_face:'))
# print(emoji.emojize(':new_moon_with_face:'))
print(emoji.emojize(':new_moon:'))
print(emoji.emojize(':waxing_crescent_moon:'))
print(emoji.emojize(':first_quarter_moon:'))
print(emoji.emojize(':waxing_gibbous_moon:'))
print(emoji.emojize(':full_moon:'))
print(emoji.emojize(':waning_gibbous_moon:'))
print(emoji.emojize(':last_quarter_moon:'))
print(emoji.emojize(':waning_crescent_moon:'))
# print(emoji.emojize(':last_quarter_moon_with_face:'))
# print(emoji.emojize(':first_quarter_moon_with_face:'))
print(emoji.emojize(':crescent_moon:'))
# print(emoji.emojize(':earth_africa:'))
# print(emoji.emojize(':earth_americas:'))
# print(emoji.emojize(':earth_asia:'))
print(emoji.emojize(':volcano:'))
print(emoji.emojize(':milky_way:'))
# print(emoji.emojize(':partly_sunny:'))
# print(emoji.emojize(':octocat:'))
# print(emoji.emojize(':squirrel:'))

# print(emoji.emojize(':bamboo:'))
# print(emoji.emojize(':gift_heart:'))
# print(emoji.emojize(':dolls:'))
# print(emoji.emojize(':school_satchel:'))
# print(emoji.emojize(':mortar_board:'))
# print(emoji.emojize(':flags:'))
print(emoji.emojize(':fireworks:'))
print(emoji.emojize(':sparkler:'))
print(emoji.emojize(':wind_chime:'))
# print(emoji.emojize(':rice_scene:'))
# print(emoji.emojize(':jack_o_lantern:'))
print(emoji.emojize(':ghost:'))
# print(emoji.emojize(':santa:'))
# print(emoji.emojize(':christmas_tree:'))
# print(emoji.emojize(':gift:'))
print(emoji.emojize(':bell:'))
# print(emoji.emojize(':no_bell:'))
print(emoji.emojize(':tanabata_tree:'))
# print(emoji.emojize(':tada:'))
print(emoji.emojize(':confetti_ball:'))
print(emoji.emojize(':balloon:'))
print(emoji.emojize(':crystal_ball:'))
# print(emoji.emojize(':cd:'))
print(emoji.emojize(':dvd:'))
print(emoji.emojize(':floppy_disk:'))
print(emoji.emojize(':camera:'))
print(emoji.emojize(':video_camera:'))
print(emoji.emojize(':movie_camera:'))
# print(emoji.emojize(':computer:'))
# print(emoji.emojize(':tv:'))
# print(emoji.emojize(':iphone:'))
# print(emoji.emojize(':phone:'))
print(emoji.emojize(':telephone:'))
print(emoji.emojize(':telephone_receiver:'))
print(emoji.emojize(':pager:'))
# print(emoji.emojize(':fax:'))
# print(emoji.emojize(':minidisc:'))
# print(emoji.emojize(':vhs:'))
# print(emoji.emojize(':sound:'))
# print(emoji.emojize(':speaker:'))
# print(emoji.emojize(':mute:'))
print(emoji.emojize(':loudspeaker:'))
# print(emoji.emojize(':mega:'))
# print(emoji.emojize(':hourglass:'))
# print(emoji.emojize(':hourglass_flowing_sand:'))
print(emoji.emojize(':alarm_clock:'))
print(emoji.emojize(':watch:'))
print(emoji.emojize(':radio:'))
print(emoji.emojize(':satellite:'))
# print(emoji.emojize(':loop:'))
# print(emoji.emojize(':mag:'))
# print(emoji.emojize(':mag_right:'))
# print(emoji.emojize(':unlock:'))
# print(emoji.emojize(':lock:'))
# print(emoji.emojize(':lock_with_ink_pen:'))
# print(emoji.emojize(':closed_lock_with_key:'))
print(emoji.emojize(':key:'))
# print(emoji.emojize(':bulb:'))
print(emoji.emojize(':flashlight:'))
# print(emoji.emojize(':high_brightness:'))
# print(emoji.emojize(':low_brightness:'))
print(emoji.emojize(':electric_plug:'))
print(emoji.emojize(':battery:'))
# print(emoji.emojize(':calling:'))
# print(emoji.emojize(':email:'))
# print(emoji.emojize(':mailbox:'))
print(emoji.emojize(':postbox:'))
# print(emoji.emojize(':bath:'))
print(emoji.emojize(':bathtub:'))
print(emoji.emojize(':shower:'))
print(emoji.emojize(':toilet:'))
print(emoji.emojize(':wrench:'))
print(emoji.emojize(':nut_and_bolt:'))
print(emoji.emojize(':hammer:'))
print(emoji.emojize(':seat:'))
# print(emoji.emojize(':moneybag:'))
# print(emoji.emojize(':yen:'))
# print(emoji.emojize(':dollar:'))
# print(emoji.emojize(':pound:'))
# print(emoji.emojize(':euro:'))
print(emoji.emojize(':credit_card:'))
print(emoji.emojize(':money_with_wings:'))
print(emoji.emojize(':e-mail:'))
print(emoji.emojize(':inbox_tray:'))
print(emoji.emojize(':outbox_tray:'))
print(emoji.emojize(':envelope:'))
print(emoji.emojize(':incoming_envelope:'))
print(emoji.emojize(':postal_horn:'))
# print(emoji.emojize(':mailbox_closed:'))
# print(emoji.emojize(':mailbox_with_mail:'))
# print(emoji.emojize(':mailbox_with_no_mail:'))
print(emoji.emojize(':package:'))
print(emoji.emojize(':door:'))
# print(emoji.emojize(':smoking:'))
print(emoji.emojize(':bomb:'))
# print(emoji.emojize(':gun:'))
# print(emoji.emojize(':hocho:'))
print(emoji.emojize(':pill:'))
print(emoji.emojize(':syringe:'))
print(emoji.emojize(':page_facing_up:'))
print(emoji.emojize(':page_with_curl:'))
print(emoji.emojize(':bookmark_tabs:'))
print(emoji.emojize(':bar_chart:'))
# print(emoji.emojize(':chart_with_upwards_trend:'))
# print(emoji.emojize(':chart_with_downwards_trend:'))
print(emoji.emojize(':scroll:'))
print(emoji.emojize(':clipboard:'))
print(emoji.emojize(':calendar:'))
# print(emoji.emojize(':date:'))
print(emoji.emojize(':card_index:'))
print(emoji.emojize(':file_folder:'))
print(emoji.emojize(':open_file_folder:'))
print(emoji.emojize(':scissors:'))
print(emoji.emojize(':pushpin:'))
print(emoji.emojize(':paperclip:'))
print(emoji.emojize(':black_nib:'))
# print(emoji.emojize(':pencil2:'))
print(emoji.emojize(':straight_ruler:'))
print(emoji.emojize(':triangular_ruler:'))
print(emoji.emojize(':closed_book:'))
print(emoji.emojize(':green_book:'))
print(emoji.emojize(':blue_book:'))
print(emoji.emojize(':orange_book:'))
print(emoji.emojize(':notebook:'))
print(emoji.emojize(':notebook_with_decorative_cover:'))
print(emoji.emojize(':ledger:'))
print(emoji.emojize(':books:'))
print(emoji.emojize(':bookmark:'))
print(emoji.emojize(':name_badge:'))
print(emoji.emojize(':microscope:'))
print(emoji.emojize(':telescope:'))
print(emoji.emojize(':newspaper:'))
# print(emoji.emojize(':football:'))
print(emoji.emojize(':basketball:'))
# print(emoji.emojize(':soccer:'))
print(emoji.emojize(':baseball:'))
print(emoji.emojize(':tennis:'))
# print(emoji.emojize(':8ball:'))
print(emoji.emojize(':rugby_football:'))
print(emoji.emojize(':bowling:'))
# print(emoji.emojize(':golf:'))
# print(emoji.emojize(':mountain_bicyclist:'))
# print(emoji.emojize(':bicyclist:'))
print(emoji.emojize(':horse_racing:'))
print(emoji.emojize(':snowboarder:'))
# print(emoji.emojize(':swimmer:'))
# print(emoji.emojize(':surfer:'))
# print(emoji.emojize(':ski:'))
# print(emoji.emojize(':spades:'))
# print(emoji.emojize(':hearts:'))
# print(emoji.emojize(':clubs:'))
# print(emoji.emojize(':diamonds:'))
# print(emoji.emojize(':gem:'))
print(emoji.emojize(':ring:'))
print(emoji.emojize(':trophy:'))
print(emoji.emojize(':musical_score:'))
print(emoji.emojize(':musical_keyboard:'))
print(emoji.emojize(':violin:'))
# print(emoji.emojize(':space_invader:'))
print(emoji.emojize(':video_game:'))
# print(emoji.emojize(':black_joker:'))
print(emoji.emojize(':flower_playing_cards:'))
print(emoji.emojize(':game_die:'))
# print(emoji.emojize(':dart:'))
# print(emoji.emojize(':mahjong:'))
# print(emoji.emojize(':clapper:'))
print(emoji.emojize(':memo:'))
print(emoji.emojize(':pencil:'))
# print(emoji.emojize(':book:'))
# print(emoji.emojize(':art:'))
print(emoji.emojize(':microphone:'))
# print(emoji.emojize(':headphones:'))
print(emoji.emojize(':trumpet:'))
print(emoji.emojize(':saxophone:'))
print(emoji.emojize(':guitar:'))
# print(emoji.emojize(':shoe:'))
# print(emoji.emojize(':sandal:'))
# print(emoji.emojize(':high_heel:'))
print(emoji.emojize(':lipstick:'))
# print(emoji.emojize(':boot:'))
# print(emoji.emojize(':shirt:'))
# print(emoji.emojize(':tshirt:'))
print(emoji.emojize(':necktie:'))
# print(emoji.emojize(':womans_clothes:'))
print(emoji.emojize(':dress:'))
# print(emoji.emojize(':running_shirt_with_sash:'))
print(emoji.emojize(':jeans:'))
print(emoji.emojize(':kimono:'))
print(emoji.emojize(':bikini:'))
print(emoji.emojize(':ribbon:'))
# print(emoji.emojize(':tophat:'))
print(emoji.emojize(':crown:'))
# print(emoji.emojize(':womans_hat:'))
# print(emoji.emojize(':mans_shoe:'))
print(emoji.emojize(':closed_umbrella:'))
print(emoji.emojize(':briefcase:'))
print(emoji.emojize(':handbag:'))
# print(emoji.emojize(':pouch:'))
print(emoji.emojize(':purse:'))
# print(emoji.emojize(':eyeglasses:'))
# print(emoji.emojize(':fishing_pole_and_fish:'))
# print(emoji.emojize(':coffee:'))
# print(emoji.emojize(':tea:'))
print(emoji.emojize(':sake:'))
print(emoji.emojize(':baby_bottle:'))
# print(emoji.emojize(':beer:'))
# print(emoji.emojize(':beers:'))
# print(emoji.emojize(':cocktail:'))
print(emoji.emojize(':tropical_drink:'))
print(emoji.emojize(':wine_glass:'))
print(emoji.emojize(':fork_and_knife:'))
print(emoji.emojize(':pizza:'))
print(emoji.emojize(':hamburger:'))
# print(emoji.emojize(':fries:'))
print(emoji.emojize(':poultry_leg:'))
print(emoji.emojize(':meat_on_bone:'))
print(emoji.emojize(':spaghetti:'))
# print(emoji.emojize(':curry:'))
print(emoji.emojize(':fried_shrimp:'))
# print(emoji.emojize(':bento:'))
print(emoji.emojize(':sushi:'))
# print(emoji.emojize(':fish_cake:'))
print(emoji.emojize(':rice_ball:'))
print(emoji.emojize(':rice_cracker:'))
# print(emoji.emojize(':rice:'))
# print(emoji.emojize(':ramen:'))
# print(emoji.emojize(':stew:'))
print(emoji.emojize(':oden:'))
print(emoji.emojize(':dango:'))
print(emoji.emojize(':egg:'))
print(emoji.emojize(':bread:'))
print(emoji.emojize(':doughnut:'))
print(emoji.emojize(':custard:'))
# print(emoji.emojize(':icecream:'))
# print(emoji.emojize(':ice_cream:'))
print(emoji.emojize(':shaved_ice:'))
# print(emoji.emojize(':birthday:'))
# print(emoji.emojize(':cake:'))
print(emoji.emojize(':cookie:'))
print(emoji.emojize(':chocolate_bar:'))
print(emoji.emojize(':candy:'))
print(emoji.emojize(':lollipop:'))
print(emoji.emojize(':honey_pot:'))
# print(emoji.emojize(':apple:'))
print(emoji.emojize(':green_apple:'))
print(emoji.emojize(':tangerine:'))
print(emoji.emojize(':lemon:'))
print(emoji.emojize(':cherries:'))
print(emoji.emojize(':grapes:'))
print(emoji.emojize(':watermelon:'))
print(emoji.emojize(':strawberry:'))
print(emoji.emojize(':peach:'))
print(emoji.emojize(':melon:'))
print(emoji.emojize(':banana:'))
print(emoji.emojize(':pear:'))
print(emoji.emojize(':pineapple:'))
# print(emoji.emojize(':sweet_potato:'))
print(emoji.emojize(':eggplant:'))
print(emoji.emojize(':tomato:'))
# print(emoji.emojize(':corn:'))

print(emoji.emojize(':house:'))
print(emoji.emojize(':house_with_garden:'))
print(emoji.emojize(':school:'))
# print(emoji.emojize(':office:'))
print(emoji.emojize(':post_office:'))
print(emoji.emojize(':hospital:'))
print(emoji.emojize(':bank:'))
print(emoji.emojize(':convenience_store:'))
print(emoji.emojize(':love_hotel:'))
print(emoji.emojize(':hotel:'))
print(emoji.emojize(':wedding:'))
print(emoji.emojize(':church:'))
print(emoji.emojize(':department_store:'))
# print(emoji.emojize(':european_post_office:'))
# print(emoji.emojize(':city_sunrise:'))
# print(emoji.emojize(':city_sunset:'))
# print(emoji.emojize(':japanese_castle:'))
# print(emoji.emojize(':european_castle:'))
print(emoji.emojize(':tent:'))
print(emoji.emojize(':factory:'))
# print(emoji.emojize(':tokyo_tower:'))
# print(emoji.emojize(':japan:'))
print(emoji.emojize(':mount_fuji:'))
print(emoji.emojize(':sunrise_over_mountains:'))
print(emoji.emojize(':sunrise:'))
# print(emoji.emojize(':stars:'))
# print(emoji.emojize(':statue_of_liberty:'))
print(emoji.emojize(':bridge_at_night:'))
print(emoji.emojize(':carousel_horse:'))
print(emoji.emojize(':rainbow:'))
print(emoji.emojize(':ferris_wheel:'))
print(emoji.emojize(':fountain:'))
print(emoji.emojize(':roller_coaster:'))
print(emoji.emojize(':ship:'))
print(emoji.emojize(':speedboat:'))
# print(emoji.emojize(':boat:'))
print(emoji.emojize(':sailboat:'))
# print(emoji.emojize(':rowboat:'))
print(emoji.emojize(':anchor:'))
print(emoji.emojize(':rocket:'))
print(emoji.emojize(':airplane:'))
print(emoji.emojize(':helicopter:'))
# print(emoji.emojize(':steam_locomotive:'))
print(emoji.emojize(':tram:'))
print(emoji.emojize(':mountain_railway:'))
# print(emoji.emojize(':bike:'))
print(emoji.emojize(':aerial_tramway:'))
print(emoji.emojize(':suspension_railway:'))
print(emoji.emojize(':mountain_cableway:'))
print(emoji.emojize(':tractor:'))
# print(emoji.emojize(':blue_car:'))
print(emoji.emojize(':oncoming_automobile:'))
# print(emoji.emojize(':car:'))
# print(emoji.emojize(':red_car:'))
print(emoji.emojize(':taxi:'))
print(emoji.emojize(':oncoming_taxi:'))
print(emoji.emojize(':articulated_lorry:'))
print(emoji.emojize(':bus:'))
print(emoji.emojize(':oncoming_bus:'))
# print(emoji.emojize(':rotating_light:'))
print(emoji.emojize(':police_car:'))
print(emoji.emojize(':oncoming_police_car:'))
print(emoji.emojize(':fire_engine:'))
print(emoji.emojize(':ambulance:'))
print(emoji.emojize(':minibus:'))
# print(emoji.emojize(':truck:'))
print(emoji.emojize(':train:'))
print(emoji.emojize(':station:'))
# print(emoji.emojize(':train2:'))
# print(emoji.emojize(':bullettrain_front:'))
# print(emoji.emojize(':bullettrain_side:'))
print(emoji.emojize(':light_rail:'))
print(emoji.emojize(':monorail:'))
print(emoji.emojize(':railway_car:'))
print(emoji.emojize(':trolleybus:'))
print(emoji.emojize(':ticket:'))
# print(emoji.emojize(':fuelpump:'))
print(emoji.emojize(':vertical_traffic_light:'))
# print(emoji.emojize(':traffic_light:'))
print(emoji.emojize(':warning:'))
print(emoji.emojize(':construction:'))
# print(emoji.emojize(':beginner:'))
# print(emoji.emojize(':atm:'))
print(emoji.emojize(':slot_machine:'))
# print(emoji.emojize(':busstop:'))
# print(emoji.emojize(':barber:'))
# print(emoji.emojize(':hotsprings:'))
# print(emoji.emojize(':checkered_flag:'))
print(emoji.emojize(':crossed_flags:'))
# print(emoji.emojize(':izakaya_lantern:'))
# print(emoji.emojize(':moyai:'))
print(emoji.emojize(':circus_tent:'))
print(emoji.emojize(':performing_arts:'))
print(emoji.emojize(':round_pushpin:'))
# print(emoji.emojize(':triangular_flag_on_post:'))
# print(emoji.emojize(':jp:'))
# print(emoji.emojize(':kr:'))
# print(emoji.emojize(':cn:'))
# print(emoji.emojize(':us:'))
# print(emoji.emojize(':fr:'))
# print(emoji.emojize(':es:'))
# print(emoji.emojize(':it:'))
# print(emoji.emojize(':ru:'))
# print(emoji.emojize(':gb:'))
# print(emoji.emojize(':uk:'))
# print(emoji.emojize(':de:'))

# print(emoji.emojize(':one:'))
# print(emoji.emojize(':two:'))
# print(emoji.emojize(':three:'))
# print(emoji.emojize(':four:'))
# print(emoji.emojize(':five:'))
# print(emoji.emojize(':six:'))
# print(emoji.emojize(':seven:'))
# print(emoji.emojize(':eight:'))
# print(emoji.emojize(':nine:'))
# print(emoji.emojize(':keycap_ten:'))
# print(emoji.emojize(':1234:'))
# print(emoji.emojize(':zero:'))
# print(emoji.emojize(':hash:'))
# print(emoji.emojize(':symbols:'))
# print(emoji.emojize(':arrow_backward:'))
# print(emoji.emojize(':arrow_down:'))
# print(emoji.emojize(':arrow_forward:'))
# print(emoji.emojize(':arrow_left:'))
# print(emoji.emojize(':capital_abcd:'))
# print(emoji.emojize(':abcd:'))
# print(emoji.emojize(':abc:'))
# print(emoji.emojize(':arrow_lower_left:'))
# print(emoji.emojize(':arrow_lower_right:'))
# print(emoji.emojize(':arrow_right:'))
# print(emoji.emojize(':arrow_up:'))
# print(emoji.emojize(':arrow_upper_left:'))
# print(emoji.emojize(':arrow_upper_right:'))
# print(emoji.emojize(':arrow_double_down:'))
# print(emoji.emojize(':arrow_double_up:'))
# print(emoji.emojize(':arrow_down_small:'))
# print(emoji.emojize(':arrow_heading_down:'))
# print(emoji.emojize(':arrow_heading_up:'))
# print(emoji.emojize(':leftwards_arrow_with_hook:'))
# print(emoji.emojize(':arrow_right_hook:'))
# print(emoji.emojize(':left_right_arrow:'))
# print(emoji.emojize(':arrow_up_down:'))
# print(emoji.emojize(':arrow_up_small:'))
# print(emoji.emojize(':arrows_clockwise:'))
# print(emoji.emojize(':arrows_counterclockwise:'))
# print(emoji.emojize(':rewind:'))
# print(emoji.emojize(':fast_forward:'))
# print(emoji.emojize(':information_source:'))
# print(emoji.emojize(':ok:'))
# print(emoji.emojize(':twisted_rightwards_arrows:'))
# print(emoji.emojize(':repeat:'))
# print(emoji.emojize(':repeat_one:'))
# print(emoji.emojize(':new:'))
# print(emoji.emojize(':top:'))
# print(emoji.emojize(':up:'))
# print(emoji.emojize(':cool:'))
# print(emoji.emojize(':free:'))
# print(emoji.emojize(':ng:'))
print(emoji.emojize(':cinema:'))
# print(emoji.emojize(':koko:'))
# print(emoji.emojize(':signal_strength:'))
# print(emoji.emojize(':u5272:'))
# print(emoji.emojize(':u5408:'))
# print(emoji.emojize(':u55b6:'))
# print(emoji.emojize(':u6307:'))
# print(emoji.emojize(':u6708:'))
# print(emoji.emojize(':u6709:'))
# print(emoji.emojize(':u6e80:'))
# print(emoji.emojize(':u7121:'))
# print(emoji.emojize(':u7533:'))
# print(emoji.emojize(':u7a7a:'))
# print(emoji.emojize(':u7981:'))
# print(emoji.emojize(':sa:'))
print(emoji.emojize(':restroom:'))
# print(emoji.emojize(':mens:'))
# print(emoji.emojize(':womens:'))
print(emoji.emojize(':baby_symbol:'))
print(emoji.emojize(':no_smoking:'))
# print(emoji.emojize(':parking:'))
# print(emoji.emojize(':wheelchair:'))
print(emoji.emojize(':metro:'))
print(emoji.emojize(':baggage_claim:'))
# print(emoji.emojize(':accept:'))
# print(emoji.emojize(':wc:'))
print(emoji.emojize(':potable_water:'))
# print(emoji.emojize(':put_litter_in_its_place:'))
# print(emoji.emojize(':secret:'))
# print(emoji.emojize(':congratulations:'))
# print(emoji.emojize(':m:'))
print(emoji.emojize(':passport_control:'))
print(emoji.emojize(':left_luggage:'))
print(emoji.emojize(':customs:'))
# print(emoji.emojize(':ideograph_advantage:'))
# print(emoji.emojize(':cl:'))
# print(emoji.emojize(':sos:'))
# print(emoji.emojize(':id:'))
# print(emoji.emojize(':no_entry_sign:'))
# print(emoji.emojize(':underage:'))
print(emoji.emojize(':no_mobile_phones:'))
# print(emoji.emojize(':do_not_litter:'))
print(emoji.emojize(':non-potable_water:'))
print(emoji.emojize(':no_bicycles:'))
print(emoji.emojize(':no_pedestrians:'))
print(emoji.emojize(':children_crossing:'))
print(emoji.emojize(':no_entry:'))
# print(emoji.emojize(':eight_spoked_asterisk:'))
print(emoji.emojize(':sparkle:'))
# print(emoji.emojize(':eight_pointed_black_star:'))
print(emoji.emojize(':heart_decoration:'))
# print(emoji.emojize(':vs:'))
print(emoji.emojize(':vibration_mode:'))
print(emoji.emojize(':mobile_phone_off:'))
# print(emoji.emojize(':chart:'))
print(emoji.emojize(':currency_exchange:'))
# print(emoji.emojize(':aries:'))
# print(emoji.emojize(':taurus:'))
# print(emoji.emojize(':gemini:'))
# print(emoji.emojize(':cancer:'))
# print(emoji.emojize(':leo:'))
# print(emoji.emojize(':virgo:'))
# print(emoji.emojize(':libra:'))
# print(emoji.emojize(':scorpius:'))
# print(emoji.emojize(':sagittarius:'))
# print(emoji.emojize(':capricorn:'))
# print(emoji.emojize(':aquarius:'))
# print(emoji.emojize(':pisces:'))
# print(emoji.emojize(':ophiuchus:'))
# print(emoji.emojize(':six_pointed_star:'))
# print(emoji.emojize(':negative_squared_cross_mark:'))
# print(emoji.emojize(':a:'))
# print(emoji.emojize(':b:'))
# print(emoji.emojize(':ab:'))
# print(emoji.emojize(':o2:'))
# print(emoji.emojize(':diamond_shape_with_a_dot_inside:'))
# print(emoji.emojize(':recycle:'))
# print(emoji.emojize(':end:'))
# print(emoji.emojize(':back:'))
# print(emoji.emojize(':on:'))
# print(emoji.emojize(':soon:'))
# print(emoji.emojize(':clock1:'))
# print(emoji.emojize(':clock130:'))
# print(emoji.emojize(':clock10:'))
# print(emoji.emojize(':clock1030:'))
# print(emoji.emojize(':clock11:'))
# print(emoji.emojize(':clock1130:'))
# print(emoji.emojize(':clock12:'))
# print(emoji.emojize(':clock1230:'))
# print(emoji.emojize(':clock2:'))
# print(emoji.emojize(':clock230:'))
# print(emoji.emojize(':clock3:'))
# print(emoji.emojize(':clock330:'))
# print(emoji.emojize(':clock4:'))
# print(emoji.emojize(':clock430:'))
# print(emoji.emojize(':clock5:'))
# print(emoji.emojize(':clock530:'))
# print(emoji.emojize(':clock6:'))
# print(emoji.emojize(':clock630:'))
# print(emoji.emojize(':clock7:'))
# print(emoji.emojize(':clock730:'))
# print(emoji.emojize(':clock8:'))
# print(emoji.emojize(':clock830:'))
# print(emoji.emojize(':clock9:'))
# print(emoji.emojize(':clock930:'))
print(emoji.emojize(':heavy_dollar_sign:'))
print(emoji.emojize(':copyright:'))
print(emoji.emojize(':registered:'))
# print(emoji.emojize(':tm:'))
# print(emoji.emojize(':x:'))
# print(emoji.emojize(':heavy_exclamation_mark:'))
# print(emoji.emojize(':bangbang:'))
# print(emoji.emojize(':interrobang:'))
# print(emoji.emojize(':o:'))
print(emoji.emojize(':heavy_multiplication_x:'))
print(emoji.emojize(':heavy_plus_sign:'))
print(emoji.emojize(':heavy_minus_sign:'))
print(emoji.emojize(':heavy_division_sign:'))
print(emoji.emojize(':white_flower:'))
# print(emoji.emojize(':100:'))
print(emoji.emojize(':heavy_check_mark:'))
print(emoji.emojize(':ballot_box_with_check:'))
print(emoji.emojize(':radio_button:'))  #buttono
print(emoji.emojize(':link:'))
print(emoji.emojize(':curly_loop:'))
print(emoji.emojize(':wavy_dash:'))
print(emoji.emojize(':part_alternation_mark:'))
# print(emoji.emojize(':trident:'))
print(emoji.emojize(':black_small_square:'))
print(emoji.emojize(':white_small_square:'))
# print(emoji.emojize(':black_medium_small_square:'))
# print(emoji.emojize(':white_medium_small_square:'))
print(emoji.emojize(':black_medium_square:'))
print(emoji.emojize(':white_medium_square:'))
print(emoji.emojize(':black_large_square:'))
print(emoji.emojize(':white_large_square:'))
# print(emoji.emojize(':white_check_mark:'))
print(emoji.emojize(':black_square_button:'))
print(emoji.emojize(':white_square_button:'))
print(emoji.emojize(':black_circle:'))
print(emoji.emojize(':white_circle:'))
print(emoji.emojize(':red_circle:'))
# print(emoji.emojize(':large_blue_circle:'))
print(emoji.emojize(':large_blue_diamond:'))
print(emoji.emojize(':large_orange_diamond:'))
print(emoji.emojize(':small_blue_diamond:'))
print(emoji.emojize(':small_orange_diamond:'))
# print(emoji.emojize(':small_red_triangle:'))
# print(emoji.emojize(':small_red_triangle_down:'))
# print(emoji.emojize(':shipit:'))
